mongouri: ""
redis-enabled: false

staff-items:
  - itemName: "vanish-disable"
    id: 351
    amount: 1
    damage: 10
    displayName: "&r&cVanish off"
    slot: 1
  -
    itemName: "vanish-enable"
    id: 351
    amount: 1
    damage: 0
    displayName: "&r&aVanish on"
    slot: 1
  -
    itemName: "Teleport"
    id: 345
    amount: 1
    displayName: "&r&bIr a un jugador aleatorio"
    slot: 2
    action: "vanish"
  -
    itemName: "Configuration"
    id: 101
    amount: 1
    displayName: "&9&lConfiguration"
    slot: 8